spring.application.name=enotes_api_service

spring.datasource.url=jdbc:mysql://localhost:3306/enotes
spring.datasource.username=root
spring.datasource.password=Heer@9022783870
spring.jpa.show-sql=true

#Hibenate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

file.upload.path=notes/

#Email Send
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhanvibhanushali@gmail.com
spring.mail.password=onwo oagh jmrb kydr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

